### ISSUE TITLE
Excerpt OR description?

### ISSUE THREAD

**Issue by IcecreamBurglar** [barryclark/jekyll-now#1089]
So I'm brand-new to html and basically everything web.
But I'd love if when the front page is iterating posts, it would use the "description" meta in each post if it exists. If it doesn't exist, I'd like for it to go back to the excerpt thingy. Is this possible?
Thanks.

**Comment by ldjb** [comment]
Hi, this is absolutely possible. There are two solutions I would like to share with you.

The first solution is instead of putting the description in a field called `description`, put it in a field called `excerpt`. The front matter of your post would look a bit like:

```yml
---
layout: post
title: Hello, world!
excerpt: The quick brown fox jumps over the lazy dog.
---
```

Jekyll automatically looks for a field called `excerpt` and will use that if available.

The second solution is a bit more complicated, but works if for some reason the description cannot be in a field called `excerpt`. Suppose you want it in a field called `description`. In that case, open up your `index.html` file in a text editor (or just edit it on GitHub.com), and look for the following lines:

```liquid
<div class="entry">
  {{ post.excerpt }}
</div>
```

Change that to:

```liquid
<div class="entry">
  {% if post.description %}
    {{ post.description }}
  {% else %}
    {{ post.excerpt }}
  {% endif %}
</div>
```

You will then be able to specify each post's description in its `description` front matter field, and it will fall back on the excerpt if this does not exist. The front matter in this case would look like:

```yml
---
layout: post
title: Hello, world!
description: The quick brown fox jumps over the lazy dog.
---
```

I hope this helps.
