### ISSUE TITLE
How to make the title header stay at top while scrolling down without any div overlap?

### ISSUE THREAD

**Issue by sudipidus** [barryclark/jekyll-now#1215]
looking for some example

**Comment by ldjb** [comment]
Hi, you should be able to achieve this by including something like the following in your `style.scss` file:

```css
div.wrapper-masthead {
  background: inherit;
  position: sticky;
  top: 0;
}
```

Do note that this may cause usability issues if the browser window has insufficient height (this may especially be the case for mobile devices in landscape mode). It may therefore be a good idea to, for example, use media queries to only apply the above CSS to browsers with enough height.
