### ISSUE TITLE
Provide border line in Code Cell in Jekyll

### ISSUE THREAD

**Issue by innat** [barryclark/jekyll-now#1269]
Following is the current form of code cell in jekyll ,

![now](https://user-images.githubusercontent.com/17668390/44393856-937d4b80-a557-11e8-8629-d9b9cc2ccafb.JPG)

How to provide border around the code cell, like following,

![want](https://user-images.githubusercontent.com/17668390/44393914-bc9ddc00-a557-11e8-8888-a93d7fe19da5.png)

Here is the portion from my `_config.yml` file 

```
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  auto_ids: true
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge 
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded # You might prefer to minify using :compressed
```

and here is the [style.scss](https://github.com/iphton/iphton.github.io/blob/master/style.scss).

Any suggestion will be highly appreciated.
