### ISSUE TITLE
Fix layout to avatar title on top / menu below

### ISSUE THREAD

**Issue by jmbh** [barryclark/jekyll-now#1303]
If I make my browser window narrow enough, the layout switches to having the avatar / website title / menu stacked on top of each other.

Since the usual layout doesn't give me enough space for the menu, I was wondering whether it is possible to switch to this setup entirely?

Thanks!

**Comment by gabegm** [comment]
I fixed this issue by adding a padding-top element to site-info in style.css@190
```css
.site-info {
  float: left;

  @include mobile {
    float: none;
    display: block;
    margin: 0 auto;
    padding-top: 20px;
  }
}
```
