### ISSUE TITLE
Displaying tags in posts?

### ISSUE THREAD

**Issue by dnaeon** [barryclark/jekyll-now#214]
Pretty new to Jekyll and Github pages, but after looking around for how to add tags in posts it appears that I should be using ``tags`` in the post front matter, similar to this:

```yaml
layout: post
title: My Title Goes Here
tags: tag1 tag2 tag3
```

However doing that in Jekyll Now doesn't seem to display the tags.

How can I display the tags a post has or create a block of tags used in the blog site, which would allow easier user navigation?

Thanks,
Marin
