### ISSUE TITLE
Using Custom Fonts

### ISSUE THREAD

**Issue by cesards** [barryclark/jekyll-now#368]
Hi!

I've been trying to add custom fonts to the project, but I don't know why the project is not getting the font files. Anyone has tried to add custom files?

My __`style.scss`__ contains:
```css
---
---

... 

@import "reset";
@import "colors";
@import "measures";
@import "fonts";

...

body {
    font-family: $bodyFontFamily;
} 
```

And my __`_fonts.scss`__
```css
@import url("//hello.myfonts.net/count/3006d4");

@font-face {
	font-family: 'FreightTextProMedium-Regular';
	src: url('webfonts/3006D4_0_0.eot');
	src: url('webfonts/3006D4_0_0.eot?#iefix') format('embedded-opentype'),url('webfonts/3006D4_0_0.woff2') format('woff2'),url('webfonts/3006D4_0_0.woff') format('woff'),url('webfonts/3006D4_0_0.ttf') format('truetype');
}

@font-face {font-family: 'CallunaSans-Bold';
	src: url('webfonts/3006D4_1_0.eot');
	src: url('webfonts/3006D4_1_0.eot?#iefix') format('embedded-opentype'),url('webfonts/3006D4_1_0.woff2') format('woff2'),url('webfonts/3006D4_1_0.woff') format('woff'),url('webfonts/3006D4_1_0.ttf') format('truetype');
}

$bodyFontFamily: 'FreightTextProMedium-Regular', Georgia, Cambria, 'Times New Roman', Times, serif;
```
Here is the folder tree (I tried to use assets folder before but it didn't work either)
![screen shot 2016-01-01 at 18 56 59](https://cloud.githubusercontent.com/assets/1536079/12071837/799f6562-b0b9-11e5-8cc7-7edc5a6bf472.png)

Do I have to do anything else? I've been looking for a while with no success :-(
